# Change these first
owner: justudin # Your GitHub organization or username, where this repository lives
repo: tsp-status # The name of this repository
assignees:
  - justudin

sites:
  - name: Main Website
    icon: https://tecnoscientifica.com/assets/img/favicons/favicon-32x32.png
    url: https://tecnoscientifica.com
  - name: Journals
    icon: https://tecnoscientifica.com/assets/img/favicons/favicon-32x32.png
    url: https://tecnoscientifica.com/journal/tasp

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tecnoscientifica.com
  favicon: https://tecnoscientifica.com/assets/img/favicons/favicon-32x32.png
  logoUrl: https://tecnoscientifica.com/assets/img/logos/tsp-logo-color.svg
  name: Status Page
  introTitle: "Tecno Scientifica **uptime monitor** and **status page**."
  #introMessage: "**Tecno Scientifica** uptime monitor and status page."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
