owner: justudin
repo: tsp-status
assignees:
  - justudin
  
sites:
  - name: Main Website
    icon: https://tecnoscientifica.com/assets/img/favicons/favicon-32x32.png
    url: https://tecnoscientifica.com
  - name: Journals
    icon: https://tecnoscientifica.com/assets/img/favicons/favicon-32x32.png
    url: https://tecnoscientifica.com/journal/tasp

status-website:
  cname: status.tecnoscientifica.com
  favicon: https://tecnoscientifica.com/assets/img/favicons/favicon-32x32.png
  logoUrl: https://tecnoscientifica.com/assets/img/logos/tsp-logo-color.svg
  name: Status Page - Tecno Scientifica Publishing
  hideNavTitle: true
  introTitle: "Tecno Scientifica **uptime monitor** and **status page**."

i18n:
  footer: "[Tecno Scientifica Publishing](https://tecnoscientifica.com) - *Advancing Technological Innovation and Science World.*"
